{% set name = "pytest-plus" %}
{% set version = "0.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytest-plus-{{ version }}.tar.gz
  sha256: 750ed025dec22cff1c5a6f693ebfcd7d444b5fc4866b40513187e5ce96ff1f98

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python >=3.5
    - setuptools_scm >=1.15.0
    - setuptools_scm_git_archive >=1.0
  run:
    - pytest >=3.50
    - python >=3.5

test:
  imports:
    - pytest_plus
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pycontribs/pytest-plus
  summary: 'PyTest Plus Plugin :: extends pytest functionality'
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tschoonj
